// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szgajjcjimqhkfhogawb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6Z2FqamNqaW1xaGtmaG9nYXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTY2NjIsImV4cCI6MjA1OTA3MjY2Mn0.k5FDPPH8SVKuBzyiHgm-g6ovK0T1N6yMSexBPfTj_0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);